image: node:18-alpine3.20

stages:
  - deploy

create-pages:
  stage: deploy
  tags:
    - default
  script:
  - yarn install
  - yarn build
  - mv ./build public
  pages: true
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
